name: Linting
permissions:
  contents: read

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:

  lint:

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4.1
      with:
        python-version: ${{ matrix.python-version }}
        # The target architecture (x86, x64) of the Python interpreter.
        # architecture: # optional
        version: 2.25.2
        cache: true
        cache-dependency-path: ./py${{ matrix.python-version }}.lock

    - name: Install dependencies
      run: pdm install --frozen-lockfile -L ./py${{ matrix.python-version }}.lock

    - name: Analyzing the code with pylint
      run: pdm run pylint src
