name: Release and publish
permissions:
  contents: write

on:
  push:
    tags:
      - "v*"


jobs:

  publish-to-pypi:

    name: Publish distribution to PyPI
    runs-on: ubuntu-latest
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:

      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1
        with:
          # The target architecture (x86, x64) of the Python interpreter.
          # architecture: # optional
          version: 2.25.2
          cache: true

      - name: Publish package distributions to PyPI
        run: pdm publish
